[package]
name = "hyper-rs-training"
version = "0.1.0"
authors = ["letusfly85 <letusfly95@gmail.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
